export const data = [
  {
    adult: false,
    backdrop_path: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
    genre_ids: [18, 80],
    id: 278,
    original_language: "en",
    original_title: "The Shawshank Redemption",
    overview:
      "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    popularity: 226.955,
    poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    release_date: "1994-09-23",
    title: "The Shawshank Redemption",
    video: false,
    vote_average: 8.7,
    vote_count: 27050,
  },
  {
    adult: false,
    backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    genre_ids: [18, 80],
    id: 238,
    original_language: "en",
    original_title: "The Godfather",
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    popularity: 218.755,
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    release_date: "1972-03-14",
    title: "The Godfather",
    video: false,
    vote_average: 8.691,
    vote_count: 20543,
  },
  {
    adult: false,
    backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
    genre_ids: [18, 80],
    id: 240,
    original_language: "en",
    original_title: "The Godfather Part II",
    overview:
      "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    popularity: 99.686,
    poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    release_date: "1974-12-20",
    title: "The Godfather Part II",
    video: false,
    vote_average: 8.574,
    vote_count: 12389,
  },
  {
    adult: false,
    backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
    genre_ids: [18, 36, 10752],
    id: 424,
    original_language: "en",
    original_title: "Schindler's List",
    overview:
      "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    popularity: 103.07,
    poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    release_date: "1993-12-15",
    title: "Schindler's List",
    video: false,
    vote_average: 8.565,
    vote_count: 15799,
  },
  {
    adult: false,
    backdrop_path: "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
    genre_ids: [18],
    id: 389,
    original_language: "en",
    original_title: "12 Angry Men",
    overview:
      "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    popularity: 65.41,
    poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
    release_date: "1957-04-10",
    title: "12 Angry Men",
    video: false,
    vote_average: 8.545,
    vote_count: 8599,
  },
  {
    adult: false,
    backdrop_path: "/4zlOPT9CrtIX05bBIkYxNZsm5zN.jpg",
    genre_ids: [16, 878, 10751],
    id: 1184918,
    original_language: "en",
    original_title: "The Wild Robot",
    overview:
      "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
    popularity: 5275.345,
    poster_path: "/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
    release_date: "2024-09-12",
    title: "The Wild Robot",
    video: false,
    vote_average: 8.5,
    vote_count: 2311,
  },
  {
    adult: false,
    backdrop_path: "/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg",
    genre_ids: [16, 10751, 14],
    id: 129,
    original_language: "ja",
    original_title: "千と千尋の神隠し",
    overview:
      "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    popularity: 118.144,
    poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    release_date: "2001-07-20",
    title: "Spirited Away",
    video: false,
    vote_average: 8.5,
    vote_count: 16442,
  },
  {
    adult: false,
    backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
    genre_ids: [35, 18, 10749],
    id: 19404,
    original_language: "hi",
    original_title: "दिलवाले दुल्हनिया ले जायेंगे",
    overview:
      "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    popularity: 41.291,
    poster_path: "/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg",
    release_date: "1995-10-20",
    title: "Dilwale Dulhania Le Jayenge",
    video: false,
    vote_average: 8.5,
    vote_count: 4431,
  },
  {
    adult: false,
    backdrop_path: "/oOv2oUXcAaNXakRqUPxYq5lJURz.jpg",
    genre_ids: [18, 28, 80, 53],
    id: 155,
    original_language: "en",
    original_title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    popularity: 161.449,
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-16",
    title: "The Dark Knight",
    video: false,
    vote_average: 8.516,
    vote_count: 32798,
  },
  {
    adult: false,
    backdrop_path: "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
    genre_ids: [14, 18, 80],
    id: 497,
    original_language: "en",
    original_title: "The Green Mile",
    overview:
      "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
    popularity: 78.441,
    poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
    release_date: "1999-12-10",
    title: "The Green Mile",
    video: false,
    vote_average: 8.507,
    vote_count: 17360,
  },
  {
    adult: false,
    backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    genre_ids: [35, 53, 18],
    id: 496243,
    original_language: "ko",
    original_title: "기생충",
    overview:
      "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    popularity: 137.134,
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    release_date: "2019-05-30",
    title: "Parasite",
    video: false,
    vote_average: 8.5,
    vote_count: 18194,
  },
  {
    adult: false,
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    genre_ids: [53, 80],
    id: 680,
    original_language: "en",
    original_title: "Pulp Fiction",
    overview:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    popularity: 115.327,
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: "1994-09-10",
    title: "Pulp Fiction",
    video: false,
    vote_average: 8.5,
    vote_count: 27827,
  },
  {
    adult: false,
    backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
    genre_ids: [16, 10749, 18],
    id: 372058,
    original_language: "ja",
    original_title: "君の名は。",
    overview:
      "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    popularity: 90.936,
    poster_path: "/vfJFJPepRKapMd5G2ro7klIRysq.jpg",
    release_date: "2016-08-26",
    title: "Your Name.",
    video: false,
    vote_average: 8.5,
    vote_count: 11325,
  },
  {
    adult: false,
    backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
    genre_ids: [12, 14, 28],
    id: 122,
    original_language: "en",
    original_title: "The Lord of the Rings: The Return of the King",
    overview:
      "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​",
    popularity: 187.121,
    poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    release_date: "2003-12-17",
    title: "The Lord of the Rings: The Return of the King",
    video: false,
    vote_average: 8.483,
    vote_count: 24131,
  },
  {
    adult: false,
    backdrop_path: "/ghgfzbEV7kbpbi1O8eIILKVXEA8.jpg",
    genre_ids: [35, 18, 10749],
    id: 13,
    original_language: "en",
    original_title: "Forrest Gump",
    overview:
      "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    popularity: 126.554,
    poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    release_date: "1994-06-23",
    title: "Forrest Gump",
    video: false,
    vote_average: 8.472,
    vote_count: 27360,
  },
  {
    adult: false,
    backdrop_path: "/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg",
    genre_ids: [37],
    id: 429,
    original_language: "it",
    original_title: "Il buono, il brutto, il cattivo",
    overview:
      "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
    popularity: 66.994,
    poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    release_date: "1966-12-22",
    title: "The Good, the Bad and the Ugly",
    video: false,
    vote_average: 8.463,
    vote_count: 8574,
  },
  {
    adult: false,
    backdrop_path: "/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg",
    genre_ids: [28, 18],
    id: 346,
    original_language: "ja",
    original_title: "七人の侍",
    overview:
      "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
    popularity: 44.419,
    poster_path: "/iAq0sq42vKTLneVGqHn1D4GzgrM.jpg",
    release_date: "1954-04-26",
    title: "Seven Samurai",
    video: false,
    vote_average: 8.5,
    vote_count: 3653,
  },
  {
    adult: false,
    backdrop_path: "/7TF4p86ZafnxFuNqWdhpHXFO244.jpg",
    genre_ids: [18, 80],
    id: 769,
    original_language: "en",
    original_title: "GoodFellas",
    overview:
      "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
    popularity: 80.17,
    poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    release_date: "1990-09-12",
    title: "GoodFellas",
    video: false,
    vote_average: 8.46,
    vote_count: 12808,
  },
  {
    adult: false,
    backdrop_path: "/gwj4R8Uy1GwejKqfofREKI9Jh7L.jpg",
    genre_ids: [16, 18, 10752],
    id: 12477,
    original_language: "ja",
    original_title: "火垂るの墓",
    overview:
      "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
    popularity: 0.067,
    poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
    release_date: "1988-04-16",
    title: "Grave of the Fireflies",
    video: false,
    vote_average: 8.455,
    vote_count: 5524,
  },
  {
    adult: false,
    backdrop_path: "/7lyq8hK0MhPHpUXdnqbFvZYSfkk.jpg",
    genre_ids: [18, 10749],
    id: 11216,
    original_language: "it",
    original_title: "Nuovo Cinema Paradiso",
    overview:
      "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
    popularity: 38.956,
    poster_path: "/gCI2AeMV4IHSewhJkzsur5MEp6R.jpg",
    release_date: "1988-11-17",
    title: "Cinema Paradiso",
    video: false,
    vote_average: 8.45,
    vote_count: 4346,
  },
  {
    adult: false,
    backdrop_path: "/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg",
    genre_ids: [35, 18],
    id: 637,
    original_language: "it",
    original_title: "La vita è bella",
    overview:
      "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
    popularity: 45.459,
    poster_path: "/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
    release_date: "1997-12-20",
    title: "Life Is Beautiful",
    video: false,
    vote_average: 8.4,
    vote_count: 12987,
  },
  {
    adult: false,
    backdrop_path: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    genre_ids: [12, 18, 878],
    id: 157336,
    original_language: "en",
    original_title: "Interstellar",
    overview:
      "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    popularity: 204.538,
    poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    release_date: "2014-11-05",
    title: "Interstellar",
    video: false,
    vote_average: 8.442,
    vote_count: 35484,
  },
  {
    adult: false,
    backdrop_path: "/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    genre_ids: [18],
    id: 550,
    original_language: "en",
    original_title: "Fight Club",
    overview:
      'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
    popularity: 106.266,
    poster_path: "/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    release_date: "1999-10-15",
    title: "Fight Club",
    video: false,
    vote_average: 8.439,
    vote_count: 29298,
  },
  {
    adult: false,
    backdrop_path: "/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg",
    genre_ids: [10751, 18],
    id: 667257,
    original_language: "es",
    original_title: "Cosas imposibles",
    overview:
      "After the death of her abusive husband, Matilde finds her new best friend in Miguel, her young, insecure, and disoriented neighbor.",
    popularity: 13.154,
    poster_path: "/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg",
    release_date: "2021-06-17",
    title: "Impossible Things",
    video: false,
    vote_average: 8.4,
    vote_count: 387,
  },
  {
    adult: false,
    backdrop_path: "/uif5fUshJrXyyDzfpzp1DLw3N0S.jpg",
    genre_ids: [27, 53, 9648],
    id: 539,
    original_language: "en",
    original_title: "Psycho",
    overview:
      "When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother.",
    popularity: 46.132,
    poster_path: "/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg",
    release_date: "1960-06-22",
    title: "Psycho",
    video: false,
    vote_average: 8.431,
    vote_count: 10018,
  },
  {
    adult: false,
    backdrop_path: "/uvitbjFU4JqvMwIkMWHp69bmUzG.jpg",
    genre_ids: [18, 80],
    id: 598,
    original_language: "pt",
    original_title: "Cidade de Deus",
    overview:
      "In the poverty-stricken favelas of Rio de Janeiro in the 1970s, two young men choose different paths. Rocket is a budding photographer who documents the increasing drug-related violence of his neighborhood, while José “Zé” Pequeno is an ambitious drug dealer diving into a dangerous life of crime.",
    popularity: 54.348,
    poster_path: "/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg",
    release_date: "2002-08-30",
    title: "City of God",
    video: false,
    vote_average: 8.424,
    vote_count: 7352,
  },
  {
    adult: false,
    backdrop_path: "/6Oa3zTiluBz2W8D2ou1MY16dUiF.jpg",
    genre_ids: [18],
    id: 510,
    original_language: "en",
    original_title: "One Flew Over the Cuckoo's Nest",
    overview:
      "A petty criminal fakes insanity to serve his sentence in a mental ward rather than prison. He soon finds himself as a leader to the other patients—and an enemy to the cruel, domineering nurse who runs the ward.",
    popularity: 52.912,
    poster_path: "/kjWsMh72V6d8KRLV4EOoSJLT1H7.jpg",
    release_date: "1975-11-19",
    title: "One Flew Over the Cuckoo's Nest",
    video: false,
    vote_average: 8.416,
    vote_count: 10392,
  },
  {
    adult: false,
    backdrop_path: "/uPYa165sraN2c8gZBM9C47g3JoU.jpg",
    genre_ids: [18, 80],
    id: 311,
    original_language: "en",
    original_title: "Once Upon a Time in America",
    overview:
      "A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.",
    popularity: 38.706,
    poster_path: "/7jPWSo0yn6gW72LDuZvZq29uqpG.jpg",
    release_date: "1984-05-23",
    title: "Once Upon a Time in America",
    video: false,
    vote_average: 8.416,
    vote_count: 5365,
  },
  {
    adult: false,
    backdrop_path: "/x2RS3uTcsJJ9IfjNPcgDmukoEcQ.jpg",
    genre_ids: [12, 14, 28],
    id: 120,
    original_language: "en",
    original_title: "The Lord of the Rings: The Fellowship of the Ring",
    overview:
      "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
    popularity: 278.649,
    poster_path: "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    release_date: "2001-12-18",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    video: false,
    vote_average: 8.4,
    vote_count: 25070,
  },
  {
    adult: false,
    backdrop_path: "/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg",
    genre_ids: [10749, 18],
    id: 696374,
    original_language: "en",
    original_title: "Gabriel's Inferno",
    overview:
      "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
    popularity: 21.589,
    poster_path: "/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg",
    release_date: "2020-05-29",
    title: "Gabriel's Inferno",
    video: false,
    vote_average: 8.4,
    vote_count: 2410,
  },
  {
    adult: false,
    backdrop_path: "/uBZQOYZLIU9dBmd62fdzBAoropu.jpg",
    genre_ids: [28, 12, 16, 18],
    id: 704264,
    original_language: "en",
    original_title: "Primal: Tales of Savagery",
    overview:
      "Genndy Tartakovsky's Primal: Tales of Savagery features a caveman and a dinosaur on the brink of extinction. Bonded by tragedy, this unlikely friendship becomes the only hope of survival.",
    popularity: 12.923,
    poster_path: "/9NBBkdxH0TjQEBSN2AzeE1sgsF9.jpg",
    release_date: "2019-11-21",
    title: "Primal: Tales of Savagery",
    video: false,
    vote_average: 8.403,
    vote_count: 315,
  },
  {
    adult: false,
    backdrop_path: "/nC3IjYhUgZWgfKfFX0ygMigFwgc.jpg",
    genre_ids: [28, 18, 36],
    id: 14537,
    original_language: "ja",
    original_title: "切腹",
    overview:
      "Down-on-his-luck veteran Tsugumo Hanshirō enters the courtyard of the prosperous House of Iyi. Unemployed, and with no family, he hopes to find a place to commit seppuku—and a worthy second to deliver the coup de grâce in his suicide ritual. The senior counselor for the Iyi clan questions the ronin’s resolve and integrity, suspecting Hanshirō of seeking charity rather than an honorable end. What follows is a pair of interlocking stories which lay bare the difference between honor and respect, and promises to examine the legendary foundations of the Samurai code.",
    popularity: 17.345,
    poster_path: "/5konZnIbcAxZjP616Cz5o9bKEfW.jpg",
    release_date: "1962-09-15",
    title: "Harakiri",
    video: false,
    vote_average: 8.4,
    vote_count: 987,
  },
  {
    adult: false,
    backdrop_path: "/alQqTpmEkxSLgajfEYTsTH6nAKB.jpg",
    genre_ids: [35, 18, 14],
    id: 40096,
    original_language: "pt",
    original_title: "O Auto da Compadecida",
    overview:
      "The lively João Grilo and the sly Chicó are poor guys living in the hinterland who cheat a bunch of people in a small town in Northeastern Brazil. When they die, they have to be judged by Christ, the Devil and the Virgin Mary before they are admitted to paradise.",
    popularity: 11.833,
    poster_path: "/imcOp1kJsCsAFCoOtY5OnPrFbAf.jpg",
    release_date: "2000-09-15",
    title: "A Dog's Will",
    video: false,
    vote_average: 8.4,
    vote_count: 1092,
  },
  {
    adult: false,
    backdrop_path: "/xqaN2WYQclQlqvKvsOcNgOx2vRn.jpg",
    genre_ids: [14, 16, 12],
    id: 4935,
    original_language: "ja",
    original_title: "ハウルの動く城",
    overview:
      "Sophie, a young milliner, is turned into an elderly woman by a witch who enters her shop and curses her. She encounters a wizard named Howl and gets caught up in his resistance to fighting for the king.",
    popularity: 71.605,
    poster_path: "/23hUJh7JdO23SpgUB5oiFDQk2wX.jpg",
    release_date: "2004-09-09",
    title: "Howl's Moving Castle",
    video: false,
    vote_average: 8.4,
    vote_count: 9835,
  },
  {
    adult: false,
    backdrop_path: "/qGQf2OHIkoh89K8XeKQzhxczf96.jpg",
    genre_ids: [16, 28, 12, 878],
    id: 324857,
    original_language: "en",
    original_title: "Spider-Man: Into the Spider-Verse",
    overview:
      'Struggling to find his place in the world while juggling school and family, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops unfathomable powers just like the one and only Spider-Man. While wrestling with the implications of his new abilities, Miles discovers a super collider created by the madman Wilson "Kingpin" Fisk, causing others from across the Spider-Verse to be inadvertently transported to his dimension.',
    popularity: 108.578,
    poster_path: "/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    release_date: "2018-12-06",
    title: "Spider-Man: Into the Spider-Verse",
    video: false,
    vote_average: 8.4,
    vote_count: 15539,
  },
  {
    adult: false,
    backdrop_path: "/jfEOzpsjc6JDlKhUHb4toWQPt.jpg",
    genre_ids: [12, 14, 28],
    id: 121,
    original_language: "en",
    original_title: "The Lord of the Rings: The Two Towers",
    overview:
      "Frodo Baggins and the other members of the Fellowship continue on their sacred quest to destroy the One Ring--but on separate paths. Their destinies lie at two towers--Orthanc Tower in Isengard, where the corrupt wizard Saruman awaits, and Sauron's fortress at Barad-dur, deep within the dark lands of Mordor. Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.",
    popularity: 138.395,
    poster_path: "/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
    release_date: "2002-12-18",
    title: "The Lord of the Rings: The Two Towers",
    video: false,
    vote_average: 8.4,
    vote_count: 21777,
  },
  {
    adult: false,
    backdrop_path: "/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg",
    genre_ids: [10749, 18],
    id: 724089,
    original_language: "en",
    original_title: "Gabriel's Inferno: Part II",
    overview:
      "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
    popularity: 10.941,
    poster_path: "/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg",
    release_date: "2020-07-31",
    title: "Gabriel's Inferno: Part II",
    video: false,
    vote_average: 8.4,
    vote_count: 1512,
  },
  {
    adult: false,
    backdrop_path: "/4Nx40jwpoTHPjCWNGoaZ6kaoGxa.jpg",
    genre_ids: [18],
    id: 255709,
    original_language: "ko",
    original_title: "소원",
    overview:
      "After 8-year-old So-won narrowly survives a brutal sexual assault, her family labors to help her heal while coping with their own rage and grief.",
    popularity: 16.424,
    poster_path: "/x9yjkm9gIz5qI5fJMUTfBnWiB2o.jpg",
    release_date: "2013-10-02",
    title: "Hope",
    video: false,
    vote_average: 8.392,
    vote_count: 729,
  },
  {
    adult: false,
    backdrop_path: "/aJCtkxLLzkk1pECehVjKHA2lBgw.jpg",
    genre_ids: [12, 28, 878],
    id: 1891,
    original_language: "en",
    original_title: "The Empire Strikes Back",
    overview:
      "The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.",
    popularity: 38.053,
    poster_path: "/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
    release_date: "1980-05-20",
    title: "The Empire Strikes Back",
    video: false,
    vote_average: 8.4,
    vote_count: 16874,
  },
  {
    adult: false,
    backdrop_path: "/3RMLbSEXOn1CzLoNT7xFeLfdxhq.jpg",
    genre_ids: [10749, 16],
    id: 372754,
    original_language: "ja",
    original_title: "同級生",
    overview:
      "Rihito Sajo, an honor student with a perfect score on the entrance exam and Hikaru Kusakabe, in a band and popular among girls, would have never crossed paths. Until one day they started talking at the practice for their school’s upcoming chorus festival. After school, the two meet regularly, as Hikaru helps Rihito to improve his singing skills. While they listen to each other’s voice and harmonize, their hearts start to beat together.",
    popularity: 11.884,
    poster_path: "/cIfRCA5wEvj9tApca4UDUagQEiM.jpg",
    release_date: "2016-02-20",
    title: "Dou kyu sei – Classmates",
    video: false,
    vote_average: 8.391,
    vote_count: 382,
  },
  {
    adult: false,
    backdrop_path: "/5lAMQMWpXMsirvtLLvW7cJgEPkU.jpg",
    genre_ids: [16, 18],
    id: 378064,
    original_language: "ja",
    original_title: "映画 聲の形",
    overview:
      "Shouya Ishida starts bullying the new girl in class, Shouko Nishimiya, because she is deaf. But as the teasing continues, the rest of the class starts to turn on Shouya for his lack of compassion. When they leave elementary school, Shouko and Shouya do not speak to each other again... until an older, wiser Shouya, tormented by his past behaviour, decides he must see Shouko once more. He wants to atone for his sins, but is it already too late...?",
    popularity: 45.383,
    poster_path: "/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg",
    release_date: "2016-09-17",
    title: "A Silent Voice: The Movie",
    video: false,
    vote_average: 8.4,
    vote_count: 3934,
  },
  {
    adult: false,
    backdrop_path: "/gutU32BiBxJvJdzLv5RWC9hQhNh.jpg",
    genre_ids: [18],
    id: 1058694,
    original_language: "es",
    original_title: "Radical",
    overview:
      "In a Mexican border town plagued by neglect, corruption, and violence, a frustrated teacher tries an unorthodox new method to break through his students’ apathy and unlock their curiosity, their potential... and perhaps even their genius.",
    popularity: 36.945,
    poster_path: "/eGMkkbG85JUyXQEsbZKSnBrymts.jpg",
    release_date: "2023-10-19",
    title: "Radical",
    video: false,
    vote_average: 8.38,
    vote_count: 414,
  },
  {
    adult: false,
    backdrop_path: "/fQq1FWp1rC89xDrRMuyFJdFUdMd.jpg",
    genre_ids: [10749, 18],
    id: 761053,
    original_language: "en",
    original_title: "Gabriel's Inferno: Part III",
    overview:
      "The final part of the film adaption of the erotic romance novel Gabriel's Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard.",
    popularity: 27.134,
    poster_path: "/fYtHxTxlhzD4QWfEbrC1rypysSD.jpg",
    release_date: "2020-11-19",
    title: "Gabriel's Inferno: Part III",
    video: false,
    vote_average: 8.4,
    vote_count: 1053,
  },
  {
    adult: false,
    backdrop_path: "/5h8VtV4oh2qkO8Iqz7gypIYJPAr.jpg",
    genre_ids: [18, 10402],
    id: 244786,
    original_language: "en",
    original_title: "Whiplash",
    overview:
      "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
    popularity: 92.451,
    poster_path: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    release_date: "2014-10-10",
    title: "Whiplash",
    video: false,
    vote_average: 8.4,
    vote_count: 15020,
  },
  {
    adult: false,
    backdrop_path: "/hchJ0PTREmXveasCBsT4SdPY3JF.jpg",
    genre_ids: [18, 10752],
    id: 423,
    original_language: "en",
    original_title: "The Pianist",
    overview:
      "The true story of pianist Władysław Szpilman's experiences in Warsaw during the Nazi occupation. When the Jews of the city find themselves forced into a ghetto, Szpilman finds work playing in a café; and when his family is deported in 1942, he stays behind, works for a while as a laborer, and eventually goes into hiding in the ruins of the war-torn city.",
    popularity: 44.823,
    poster_path: "/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
    release_date: "2002-09-17",
    title: "The Pianist",
    video: false,
    vote_average: 8.381,
    vote_count: 9131,
  },
  {
    adult: false,
    backdrop_path: "/vxPrxPufDQc4e2zr492LkXoEjdl.jpg",
    genre_ids: [80, 9648, 53],
    id: 807,
    original_language: "en",
    original_title: "Se7en",
    overview:
      'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer\'s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.',
    popularity: 94.806,
    poster_path: "/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg",
    release_date: "1995-09-22",
    title: "Se7en",
    video: false,
    vote_average: 8.4,
    vote_count: 20915,
  },
  {
    adult: false,
    backdrop_path: "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    genre_ids: [28, 878, 12],
    id: 27205,
    original_language: "en",
    original_title: "Inception",
    overview:
      "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
    popularity: 117.706,
    poster_path: "/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg",
    release_date: "2010-07-15",
    title: "Inception",
    video: false,
    vote_average: 8.369,
    vote_count: 36474,
  },
  {
    adult: false,
    backdrop_path: "/uRKhh7JYMD6QWNt0NjmMfh7uLdm.jpg",
    genre_ids: [10402],
    id: 1160164,
    original_language: "en",
    original_title: "TAYLOR SWIFT | THE ERAS TOUR",
    overview:
      "The cultural phenomenon continues on the big screen! Immerse yourself in this once-in-a-lifetime concert film experience with a breathtaking, cinematic view of the history-making tour.",
    popularity: 35.293,
    poster_path: "/jf3YO8hOqGHCupsREf5qymYq1n.jpg",
    release_date: "2023-10-13",
    title: "TAYLOR SWIFT | THE ERAS TOUR",
    video: false,
    vote_average: 8.4,
    vote_count: 390,
  },
  {
    adult: false,
    backdrop_path: "/kVd3a9YeLGkoeR50jGEXM6EqseS.jpg",
    genre_ids: [16, 28, 12, 878],
    id: 569094,
    original_language: "en",
    original_title: "Spider-Man: Across the Spider-Verse",
    overview:
      "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
    popularity: 235.844,
    poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    release_date: "2023-05-31",
    title: "Spider-Man: Across the Spider-Verse",
    video: false,
    vote_average: 8.4,
    vote_count: 6899,
  },
  {
    adult: false,
    backdrop_path: "/aVFx1VtlOxR3v0ADEatalXOvwbu.jpg",
    genre_ids: [16, 14, 28],
    id: 620249,
    original_language: "zh",
    original_title: "罗小黑战记",
    overview:
      "When cat spirit Luo Xiaohei's home is deforested by humans, he must find a new one. He runs into a group of other spirit creatures who take him under their wing with dreams of reconquering the land they say is rightfully theirs. However, they run into a human known as Wuxian who separates Luo Xiaohei from the other spirits and the two go on a journey, with the cat spirit learning to control his abilities as well as forming his own thoughts on whether or not he should ally with the spirits or the humans.",
    popularity: 13.166,
    poster_path: "/4jfbKKLpqts3i2h2obkrONcjTg1.jpg",
    release_date: "2019-08-27",
    title: "The Legend of Hei",
    video: false,
    vote_average: 8.355,
    vote_count: 362,
  },
  {
    adult: false,
    backdrop_path: "/8aEe01VfGtYG2dFy9V5MqyyNPlh.jpg",
    genre_ids: [53, 9648],
    id: 567,
    original_language: "en",
    original_title: "Rear Window",
    overview:
      "A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.",
    popularity: 29.949,
    poster_path: "/ILVF0eJxHMddjxeQhswFtpMtqx.jpg",
    release_date: "1954-08-01",
    title: "Rear Window",
    video: false,
    vote_average: 8.351,
    vote_count: 6445,
  },
  {
    adult: false,
    backdrop_path: "/aYcnDyLMnpKce1FOYUpZrXtgUye.jpg",
    genre_ids: [80, 18, 53],
    id: 274,
    original_language: "en",
    original_title: "The Silence of the Lambs",
    overview:
      "Clarice Starling is a top student at the FBI's training academy.  Jack Crawford wants Clarice to interview Dr. Hannibal Lecter, a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism.  Crawford believes that Lecter may have insight into a case and that Starling, as an attractive young woman, may be just the bait to draw him out.",
    popularity: 22.636,
    poster_path: "/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    release_date: "1991-02-14",
    title: "The Silence of the Lambs",
    video: false,
    vote_average: 8.347,
    vote_count: 16212,
  },
  {
    adult: false,
    backdrop_path: "/mBdZ5rOB8RxluHwBfS64ZzaVanB.jpg",
    genre_ids: [18],
    id: 73,
    original_language: "en",
    original_title: "American History X",
    overview:
      "Derek Vineyard is paroled after serving 3 years in prison for killing two African-American men. Through his brother, Danny Vineyard's narration, we learn that before going to prison, Derek was a skinhead and the leader of a violent white supremacist gang that committed acts of racial crime throughout L.A. and his actions greatly influenced Danny. Reformed and fresh out of prison, Derek severs contact with the gang and becomes determined to keep Danny from going down the same violent path as he did.",
    popularity: 33.201,
    poster_path: "/euypWkaYFOLW3e5rLIcTAjWnhhT.jpg",
    release_date: "1998-07-01",
    title: "American History X",
    video: false,
    vote_average: 8.344,
    vote_count: 11489,
  },
  {
    adult: false,
    backdrop_path: "/llIXQAndg5kB6SWlp6ouUdO7Zxd.jpg",
    genre_ids: [12, 36, 28, 18, 10749, 53],
    id: 1084736,
    original_language: "fr",
    original_title: "Le Comte de Monte-Cristo",
    overview:
      "Edmond Dantes becomes the target of a sinister plot and is arrested on his wedding day for a crime he did not commit. After 14 years in the island prison of Château d’If, he manages a daring escape. Now rich beyond his dreams, he assumes the identity of the Count of Monte-Cristo and exacts his revenge on the three men who betrayed him.",
    popularity: 1773.12,
    poster_path: "/r7iCXrXmq4hKpB4QfDzZd8vsJ7l.jpg",
    release_date: "2024-06-28",
    title: "The Count of Monte-Cristo",
    video: false,
    vote_average: 8.3,
    vote_count: 729,
  },
  {
    adult: false,
    backdrop_path: "/gSCT6oP2Sbm71naW28Lh7afcMgY.jpg",
    genre_ids: [18, 80, 9648],
    id: 12493,
    original_language: "ja",
    original_title: "天国と地獄",
    overview:
      "In the midst of an attempt to take over his company, a powerhouse executive is hit with a huge ransom demand when his chauffeur's son is kidnapped by mistake.",
    popularity: 17.168,
    poster_path: "/tgNjemQPG96uIezpiUiXFcer5ga.jpg",
    release_date: "1963-03-01",
    title: "High and Low",
    video: false,
    vote_average: 8.3,
    vote_count: 898,
  },
  {
    adult: false,
    backdrop_path: "/ySaK6hpbCc2OE13ac7ovhgWwR5u.jpg",
    genre_ids: [10402],
    id: 568332,
    original_language: "en",
    original_title: "Taylor Swift: Reputation Stadium Tour",
    overview:
      "Taylor Swift takes the stage in Dallas for the Reputation Stadium Tour and celebrates a monumental night of music, memories and visual magic.",
    popularity: 16.25,
    poster_path: "/u6oXUTtOuJRPdUgUuPAVVJPSKCo.jpg",
    release_date: "2018-12-31",
    title: "Taylor Swift: Reputation Stadium Tour",
    video: false,
    vote_average: 8.337,
    vote_count: 380,
  },
  {
    adult: false,
    backdrop_path: "/gl0jzn4BupSbL2qMVeqrjKkF9Js.jpg",
    genre_ids: [12, 14, 16],
    id: 128,
    original_language: "ja",
    original_title: "もののけ姫",
    overview:
      "Ashitaka, a prince of the disappearing Emishi people, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.",
    popularity: 44.496,
    poster_path: "/cMYCDADoLKLbB83g4WnJegaZimC.jpg",
    release_date: "1997-07-12",
    title: "Princess Mononoke",
    video: false,
    vote_average: 8.3,
    vote_count: 7955,
  },
  {
    adult: false,
    backdrop_path: "/jBIMZ0AlUYuFNsKbd4L6FojWMoy.jpg",
    genre_ids: [16, 35, 10749],
    id: 820067,
    original_language: "ja",
    original_title: "映画 五等分の花嫁",
    overview:
      "When five lovely young girls who hate studying hire part-time tutor Futaro, he guides not only their education but also their hearts. Time spent has brought them all closer, with feelings growing within the girls and Futaro. As they finish their third year of high school and their last school festival approaches, they set their sights on what’s next. Is there a future with one of them and Futaro?",
    popularity: 34.775,
    poster_path: "/sg7klpt1xwK1IJirBI9EHaqQwJ5.jpg",
    release_date: "2022-05-20",
    title: "The Quintessential Quintuplets Movie",
    video: false,
    vote_average: 8.33,
    vote_count: 380,
  },
  {
    adult: false,
    backdrop_path: "/8KJMOKyl9rpgb9ELEwhfBMIaTHw.jpg",
    genre_ids: [16, 10751, 14, 35],
    id: 1139087,
    original_language: "en",
    original_title: "Once Upon a Studio",
    overview:
      "Created for Disney's 100th anniversary, the short features Mickey Mouse corralling a gallery of legendary Disney characters for a group photo.",
    popularity: 32.806,
    poster_path: "/aiy3G1cYWV3LgKZHY6a3jL8bjYL.jpg",
    release_date: "2023-09-24",
    title: "Once Upon a Studio",
    video: false,
    vote_average: 8.3,
    vote_count: 350,
  },
  {
    adult: false,
    backdrop_path: "/5bzPWQ2dFUl2aZKkp7ILJVVkRed.jpg",
    genre_ids: [12, 35, 878],
    id: 105,
    original_language: "en",
    original_title: "Back to the Future",
    overview:
      "Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently disrupting his parents' first meeting and attracting his mother's romantic interest. Marty must repair the damage to history by rekindling his parents' romance and - with the help of his eccentric inventor friend Doc Brown - return to 1985.",
    popularity: 81.927,
    poster_path: "/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg",
    release_date: "1985-07-03",
    title: "Back to the Future",
    video: false,
    vote_average: 8.317,
    vote_count: 19829,
  },
  {
    adult: false,
    backdrop_path: "/2LMgkmtnmhjUHvFXNDruHzrUFKK.jpg",
    genre_ids: [80, 18, 10749],
    id: 15804,
    original_language: "zh",
    original_title: "牯嶺街少年殺人事件",
    overview:
      "A boy experiences first love, friendships and injustices growing up in 1960s Taiwan.",
    popularity: 19.757,
    poster_path: "/rDZ2mNQkZrnSzHPLQ7SzhzgCSoj.jpg",
    release_date: "1991-07-27",
    title: "A Brighter Summer Day",
    video: false,
    vote_average: 8.317,
    vote_count: 314,
  },
  {
    adult: false,
    backdrop_path: "/A1Larywbw79kZQqkvCEiPHJqdLN.jpg",
    genre_ids: [16, 53],
    id: 10494,
    original_language: "ja",
    original_title: "PERFECT BLUE",
    overview:
      "Encouraged by her managers, rising pop star Mima takes on a recurring role on a popular TV show, when suddenly her handlers and collaborators begin turning up murdered.",
    popularity: 37.858,
    poster_path: "/6WTiOCfDPP8XV4jqfloiVWf7KHq.jpg",
    release_date: "1998-02-28",
    title: "Perfect Blue",
    video: false,
    vote_average: 8.3,
    vote_count: 2628,
  },
  {
    adult: false,
    backdrop_path: "/7itwVx4ucSluBZZ1vQfnZGx7LjA.jpg",
    genre_ids: [18],
    id: 599,
    original_language: "en",
    original_title: "Sunset Boulevard",
    overview:
      "A hack screenwriter writes a screenplay for a former silent film star who has faded into Hollywood obscurity.",
    popularity: 25.791,
    poster_path: "/sC4Dpmn87oz9AuxZ15Lmip0Ftgr.jpg",
    release_date: "1950-08-10",
    title: "Sunset Boulevard",
    video: false,
    vote_average: 8.3,
    vote_count: 2557,
  },
  {
    adult: false,
    backdrop_path: "/qknxyRgP6UTmwJ4B9tDAmzHMq7u.jpg",
    genre_ids: [10749, 16, 14],
    id: 92321,
    original_language: "ja",
    original_title: "蛍火の杜へ",
    overview:
      "One hot summer day a little girl gets lost in an enchanted forest of the mountain god where spirits reside. A young boy appears before her, but she cannot touch him for fear of making him disappear. And so a wondrous adventure awaits...",
    popularity: 0.019,
    poster_path: "/mDqzHV8UXWWNpZkoAbKmKX1ZxEE.jpg",
    release_date: "2011-09-17",
    title: "Hotarubi no Mori e",
    video: false,
    vote_average: 8.3,
    vote_count: 1101,
  },
  {
    adult: false,
    backdrop_path: "/8Lt9ljQ5IruNXtci03Hm7VcDZKe.jpg",
    genre_ids: [18],
    id: 207,
    original_language: "en",
    original_title: "Dead Poets Society",
    overview:
      "At an elite, old-fashioned boarding school in New England, a passionate English teacher inspires his students to rebel against convention and seize the potential of every day, courting the disdain of the stern headmaster.",
    popularity: 56.197,
    poster_path: "/hmGAF5NDoYB6S39UONevjHCESOI.jpg",
    release_date: "1989-06-02",
    title: "Dead Poets Society",
    video: false,
    vote_average: 8.309,
    vote_count: 11186,
  },
  {
    adult: false,
    backdrop_path: "/jynfI114q3kOAbIiVjVfFFmttU2.jpg",
    genre_ids: [80, 18, 28],
    id: 101,
    original_language: "en",
    original_title: "Léon: The Professional",
    overview:
      "Léon, the top hit man in New York, has earned a rep as an effective \"cleaner\". But when his next-door neighbors are wiped out by a loose-cannon DEA agent, he becomes the unwilling custodian of 12-year-old Mathilda. Before long, Mathilda's thoughts turn to revenge, and she considers following in Léon's footsteps.",
    popularity: 79.854,
    poster_path: "/yI6X2cCM5YPJtxMhUd3dPGqDAhw.jpg",
    release_date: "1994-09-14",
    title: "Léon: The Professional",
    video: false,
    vote_average: 8.307,
    vote_count: 14707,
  },
  {
    adult: false,
    backdrop_path: "/xLMJCCSatxENpHO9rLW9yD8A12C.jpg",
    genre_ids: [16, 878, 28, 18],
    id: 18491,
    original_language: "ja",
    original_title: "新世紀エヴァンゲリオン劇場版 Air／まごころを、君に",
    overview:
      "Seele orders an all-out attack on NERV, aiming to destroy the Evas before Gendo can trigger Third Impact and Instrumentality under his control.",
    popularity: 22.381,
    poster_path: "/j6G24dqI4WgUtChhWjfnI4lnmiK.jpg",
    release_date: "1997-07-19",
    title: "Neon Genesis Evangelion: The End of Evangelion",
    video: false,
    vote_average: 8.3,
    vote_count: 1587,
  },
  {
    adult: false,
    backdrop_path: "/c8Pi8F1FzpNebtgXcSjC9nWCdSW.jpg",
    genre_ids: [35, 10752],
    id: 914,
    original_language: "en",
    original_title: "The Great Dictator",
    overview:
      "Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel's regime.",
    popularity: 19.811,
    poster_path: "/x0L9EQuQRsIrnov5aiHXrRegaGI.jpg",
    release_date: "1940-10-15",
    title: "The Great Dictator",
    video: false,
    vote_average: 8.306,
    vote_count: 3343,
  },
  {
    adult: false,
    backdrop_path: "/1fOsyhVz5qyX2rl1qqX6KImVhTx.jpg",
    genre_ids: [18, 35],
    id: 644479,
    original_language: "es",
    original_title: "Dedicada A Mi Ex",
    overview:
      "The film tells the story of Ariel, a 21-year-old who decides to form a rock band to compete for a prize of ten thousand dollars in a musical band contest, this as a last option when trying to get money to save their relationship and reunite with his ex-girlfriend, which breaks due to the trip she must make to Finland for an internship. Ariel with her friend Ortega, decides to make a casting to find the other members of the band, although they do not know nothing about music, thus forming a band with members that have diverse and opposite personalities.",
    popularity: 10.0,
    poster_path: "/xc4bTXVwYNXi10jG9dwcaYt5IpU.jpg",
    release_date: "2019-11-01",
    title: "Dedicated to my ex",
    video: false,
    vote_average: 8.3,
    vote_count: 501,
  },
  {
    adult: false,
    backdrop_path: "/stiGp1XzkLSYdUUEWTyQOZRkr49.jpg",
    genre_ids: [18],
    id: 3782,
    original_language: "ja",
    original_title: "生きる",
    overview:
      "Kanji Watanabe is a middle-aged man who has worked in the same monotonous bureaucratic position for decades. Learning he has cancer, he starts to look for the meaning of his life.",
    popularity: 15.857,
    poster_path: "/dgNTS4EQDDVfkzJI5msKuHu2Ei3.jpg",
    release_date: "1952-10-09",
    title: "Ikiru",
    video: false,
    vote_average: 8.3,
    vote_count: 1125,
  },
  {
    adult: false,
    backdrop_path: "/kSlO1pHpwQfPQdgVPr7dJiJNtJ8.jpg",
    genre_ids: [35, 18, 10749],
    id: 3082,
    original_language: "en",
    original_title: "Modern Times",
    overview:
      "A bumbling tramp desires to build a home with a young woman, yet is thwarted time and time again by his lack of experience and habit of being in the wrong place at the wrong time..",
    popularity: 12.996,
    poster_path: "/9baQjJ85LKQZFFpNWR563SsK2rz.jpg",
    release_date: "1936-02-05",
    title: "Modern Times",
    video: false,
    vote_average: 8.293,
    vote_count: 3670,
  },
  {
    adult: false,
    backdrop_path: "/P3dkkDkRCd1CU7MT1cs0mGmH1s.jpg",
    genre_ids: [18, 37],
    id: 335,
    original_language: "it",
    original_title: "C'era una volta il West",
    overview:
      "As the railroad builders advance unstoppably through the Arizona desert on their way to the sea, Jill arrives in the small town of Flagstone with the intention of starting a new life.",
    popularity: 64.049,
    poster_path: "/qbYgqOczabWNn2XKwgMtVrntD6P.jpg",
    release_date: "1968-12-21",
    title: "Once Upon a Time in the West",
    video: false,
    vote_average: 8.288,
    vote_count: 4309,
  },
  {
    adult: false,
    backdrop_path: "/jGKQks1bd3rmltqaXbEbS9DnsPv.jpg",
    genre_ids: [16, 10751, 12, 14],
    id: 995133,
    original_language: "en",
    original_title: "The Boy, the Mole, the Fox and the Horse",
    overview:
      "The unlikely friendship of a boy, a mole, a fox and a horse traveling together in the boy's search for home.",
    popularity: 37.853,
    poster_path: "/aBBJRyS17TIrdXih3uSYvPAR3Ua.jpg",
    release_date: "2022-12-25",
    title: "The Boy, the Mole, the Fox and the Horse",
    video: false,
    vote_average: 8.282,
    vote_count: 562,
  },
  {
    adult: false,
    backdrop_path: "/n0Cju2Eu3VyrUFl32thblHFWznA.jpg",
    genre_ids: [35, 18, 10749],
    id: 901,
    original_language: "en",
    original_title: "City Lights",
    overview:
      "A tramp falls in love with a beautiful blind flower girl. His on-and-off friendship with a wealthy man allows him to be the girl's benefactor and suitor.",
    popularity: 13.045,
    poster_path: "/ugmakEL5y294I5bXgiBqApuZpwc.jpg",
    release_date: "1931-02-06",
    title: "City Lights",
    video: false,
    vote_average: 8.3,
    vote_count: 2151,
  },
  {
    adult: false,
    backdrop_path: "/bGksau9GGu0uJ8DJQ8DYc9JW5LM.jpg",
    genre_ids: [18, 35],
    id: 77338,
    original_language: "fr",
    original_title: "Intouchables",
    overview:
      "A true story of two men who should never have met – a quadriplegic aristocrat who was injured in a paragliding accident and a young man from the projects.",
    popularity: 64.883,
    poster_path: "/1QU7HKgsQbGpzsJbJK4pAVQV9F5.jpg",
    release_date: "2011-11-02",
    title: "The Intouchables",
    video: false,
    vote_average: 8.277,
    vote_count: 17136,
  },
  {
    adult: false,
    backdrop_path: "/9Qs9oyn4iE8QtQjGZ0Hp2WyYNXT.jpg",
    genre_ids: [18, 10752],
    id: 28,
    original_language: "en",
    original_title: "Apocalypse Now",
    overview:
      'At the height of the Vietnam war, Captain Benjamin Willard is sent on a dangerous mission that, officially, "does not exist, nor will it ever exist." His goal is to locate - and eliminate - a mysterious Green Beret Colonel named Walter Kurtz, who has been leading his personal army on illegal guerrilla missions into enemy territory.',
    popularity: 52.684,
    poster_path: "/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg",
    release_date: "1979-08-15",
    title: "Apocalypse Now",
    video: false,
    vote_average: 8.277,
    vote_count: 8177,
  },
  {
    adult: false,
    backdrop_path: "/rqmE0aFFerz8E8PkGOKPAoIY5Ax.jpg",
    genre_ids: [18, 10751, 14],
    id: 1585,
    original_language: "en",
    original_title: "It's a Wonderful Life",
    overview:
      "A holiday favourite for generations...  George Bailey has spent his entire life giving to the people of Bedford Falls.  All that prevents rich skinflint Mr. Potter from taking over the entire town is George's modest building and loan company.  But on Christmas Eve the business's $8,000 is lost and George's troubles begin.",
    popularity: 48.445,
    poster_path: "/bSqt9rhDZx1Q7UZ86dBPKdNomp2.jpg",
    release_date: "1946-12-20",
    title: "It's a Wonderful Life",
    video: false,
    vote_average: 8.275,
    vote_count: 4252,
  },
  {
    adult: false,
    backdrop_path: "/354kfjVb96mtFALMhBE6jzHGiA2.jpg",
    genre_ids: [10752, 18, 36],
    id: 975,
    original_language: "en",
    original_title: "Paths of Glory",
    overview:
      "A commanding officer defends three scapegoats on trial for a failed offensive that occurred within the French Army in 1916.",
    popularity: 24.305,
    poster_path: "/tJXwtzOSNUC8dxJfrdvkNtGrrgW.jpg",
    release_date: "1957-10-25",
    title: "Paths of Glory",
    video: false,
    vote_average: 8.272,
    vote_count: 2881,
  },
  {
    adult: false,
    backdrop_path: "/aLqtWLA6NQHBwQHvHDq5z4EKUm0.jpg",
    genre_ids: [16, 14, 10749, 18],
    id: 533514,
    original_language: "ja",
    original_title: "劇場版 ヴァイオレット・エヴァーガーデン",
    overview:
      "As the world moves on from the war and technological advances bring changes to her life, Violet still hopes to see her lost commanding officer again.",
    popularity: 23.53,
    poster_path: "/A9R6bukzzRmOzxvDQsXdQpeNm8l.jpg",
    release_date: "2020-09-18",
    title: "Violet Evergarden: The Movie",
    video: false,
    vote_average: 8.271,
    vote_count: 404,
  },
  {
    adult: false,
    backdrop_path: "/i1GT0e6Crg6UezT3ibXnMS3pBAd.jpg",
    genre_ids: [16, 18, 10749],
    id: 652837,
    original_language: "ja",
    original_title: "ジョゼと虎と魚たち",
    overview:
      "With dreams of diving abroad, Tsuneo gets a job assisting Josee, an artist whose imagination takes her far beyond her wheelchair. But when the tide turns against them, they push each other to places they never thought possible, and inspire a love fit for a storybook.",
    popularity: 14.863,
    poster_path: "/xAbSLi61npWyVs5M0yxin3dKcGO.jpg",
    release_date: "2020-12-25",
    title: "Josee, the Tiger and the Fish",
    video: false,
    vote_average: 8.3,
    vote_count: 462,
  },
  {
    adult: false,
    backdrop_path: "/6rmb35g7XoMCMQtnbH0rUecFZlV.jpg",
    genre_ids: [18, 10402],
    id: 10376,
    original_language: "it",
    original_title: "La leggenda del pianista sull'oceano",
    overview:
      "The story of a virtuoso piano player who lives his entire life aboard an ocean liner. Born and raised on the ship, 1900 (Tim Roth) learned about the outside world through interactions with passengers, never setting foot on land, even for the love of his life. Years later, the ship may be destroyed, and a former band member fears that 1900 may still be aboard, willing to go down with the ship.",
    popularity: 29.285,
    poster_path: "/iOcbJ5pxokOPDRgieVDbsFMrCc6.jpg",
    release_date: "1998-10-28",
    title: "The Legend of 1900",
    video: false,
    vote_average: 8.266,
    vote_count: 2236,
  },
  {
    adult: false,
    backdrop_path: "/inEy3A5OPgeYW4rjRiGycfEeQzA.jpg",
    genre_ids: [18],
    id: 637920,
    original_language: "tr",
    original_title: "7. Koğuştaki Mucize",
    overview:
      "Separated from his daughter, a father with an intellectual disability must prove his innocence when he is jailed for the death of a commander's child.",
    popularity: 37.905,
    poster_path: "/bOth4QmNyEkalwahfPCfiXjNh1r.jpg",
    release_date: "2019-10-10",
    title: "Miracle in Cell No. 7",
    video: false,
    vote_average: 8.265,
    vote_count: 4387,
  },
  {
    adult: false,
    backdrop_path: "/u1wHUA0R48FH4WV3sGqjwx3aNZm.jpg",
    genre_ids: [16, 18, 10402, 10749],
    id: 632632,
    original_language: "ja",
    original_title: "映画 ギヴン",
    overview:
      "The relationship between a band's bassist, their drummer, and the drummer’s roommate and ex-boyfriend, who is a professional violinist.",
    popularity: 16.777,
    poster_path: "/3trPz7muDOv4AHjDZiD3MLGls2Q.jpg",
    release_date: "2020-08-22",
    title: "Given",
    video: false,
    vote_average: 8.3,
    vote_count: 377,
  },
  {
    adult: false,
    backdrop_path: "/f72GEQF2lKsdmEULSI9bWCbQylH.jpg",
    genre_ids: [18, 53, 80],
    id: 29259,
    original_language: "fr",
    original_title: "Le Trou",
    overview:
      "Four prison inmates have been hatching a plan to literally dig out of jail when another prisoner, Claude Gaspard, is moved into their cell. They take a risk and share their plan with the newcomer. Over the course of three days, the prisoners and friends break through the concrete floor using a bed post and begin to make their way through the sewer system -- yet their escape is anything but assured.",
    popularity: 10.474,
    poster_path: "/8kxtOm7D992iAaOzUoWmNQwbXjs.jpg",
    release_date: "1960-03-18",
    title: "Le Trou",
    video: false,
    vote_average: 8.3,
    vote_count: 469,
  },
  {
    adult: false,
    backdrop_path: "/88J6waYVTta8Qz3iX3qUeWNA5d5.jpg",
    genre_ids: [18, 10749],
    id: 447362,
    original_language: "en",
    original_title: "Life in a Year",
    overview:
      "A 17 year old finds out that his girlfriend is dying, so he sets out to give her an entire life, in the last year she has left.",
    popularity: 63.276,
    poster_path: "/bP7u19opmHXYeTCUwGjlLldmUMc.jpg",
    release_date: "2020-11-27",
    title: "Life in a Year",
    video: false,
    vote_average: 8.259,
    vote_count: 1869,
  },
  {
    adult: false,
    backdrop_path: "/2Kkqmy3EpXqBDqv1vvsNXX3pwww.jpg",
    genre_ids: [18, 35],
    id: 42269,
    original_language: "it",
    original_title: "C'eravamo tanto amati",
    overview:
      "Three partisans bound by a strong friendship return home after the war, but the clash with everyday reality puts a strain on their bond.",
    popularity: 8.355,
    poster_path: "/zGGWYpiKNwjpKxelPxOMqJnUgDs.jpg",
    release_date: "1974-12-21",
    title: "We All Loved Each Other So Much",
    video: false,
    vote_average: 8.259,
    vote_count: 548,
  },
  {
    adult: false,
    backdrop_path: "/wXfAvsPZqBDJ8U78F2IAzsUxtNh.jpg",
    genre_ids: [10751, 16, 18],
    id: 8587,
    original_language: "en",
    original_title: "The Lion King",
    overview:
      "A young lion prince is cast out of his pride by his cruel uncle, who claims he killed his father. While the uncle rules with an iron paw, the prince grows up beyond the Savannah, living by a philosophy: No worries for the rest of your days. But when his past comes to haunt him, the young prince must decide his fate: Will he remain an outcast or face his demons and become what he needs to be?",
    popularity: 144.33,
    poster_path: "/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
    release_date: "1994-06-24",
    title: "The Lion King",
    video: false,
    vote_average: 8.259,
    vote_count: 18198,
  },
  {
    adult: false,
    backdrop_path: "/nbAbAk80aWCpOS5kOPYJ1L9kE1R.jpg",
    genre_ids: [10402, 18, 10749],
    id: 630566,
    original_language: "en",
    original_title: "Clouds",
    overview:
      "Young musician Zach Sobiech discovers his cancer has spread, leaving him just a few months to live. With limited time, he follows his dream and makes an album, unaware that it will soon be a viral music phenomenon.",
    popularity: 15.104,
    poster_path: "/d0OdD1I8qAfETvE9Rp9Voq7R8LR.jpg",
    release_date: "2020-10-09",
    title: "Clouds",
    video: false,
    vote_average: 8.258,
    vote_count: 1002,
  },
  {
    adult: false,
    backdrop_path: "/sdwjQEM869JFwMytTmvr6ggvaUl.jpg",
    genre_ids: [18, 53, 9648, 28],
    id: 670,
    original_language: "ko",
    original_title: "올드보이",
    overview:
      "With no clue how he came to be imprisoned, drugged and tortured for 15 years, a desperate man seeks revenge on his captors.",
    popularity: 55.264,
    poster_path: "/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg",
    release_date: "2003-11-21",
    title: "Oldboy",
    video: false,
    vote_average: 8.256,
    vote_count: 8618,
  },
  {
    adult: false,
    backdrop_path: "/1EAxNqdkVnp48a7NUuNBHGflowM.jpg",
    genre_ids: [16, 28, 878, 18],
    id: 283566,
    original_language: "ja",
    original_title: "シン・エヴァンゲリオン劇場版:||",
    overview:
      "In the aftermath of the Fourth Impact, stranded without their Evangelions, Shinji, Asuka and Rei find refuge in one of the rare pockets of humanity that still exist on the ruined planet Earth. There, each lives a life far different from their days as an Evangelion pilot. However, the danger to the world is far from over. A new impact is looming on the horizon—one that will prove to be the true end of Evangelion.",
    popularity: 22.622,
    poster_path: "/md5wZRRj8biHrGtyitgBZo7674t.jpg",
    release_date: "2021-03-08",
    title: "Evangelion: 3.0+1.0 Thrice Upon a Time",
    video: false,
    vote_average: 8.3,
    vote_count: 804,
  },
  {
    adult: false,
    backdrop_path: "/6C1U0cKK5zGjyUSwNc5GLSVCr7Y.jpg",
    genre_ids: [18, 10752],
    id: 25237,
    original_language: "ru",
    original_title: "Иди и смотри",
    overview:
      "The invasion of a village in Byelorussia by German forces sends young Florya into the forest to join the weary Resistance fighters, against his family's wishes. There he meets a girl, Glasha, who accompanies him back to his village. On returning home, Florya finds his family and fellow peasants massacred. His continued survival amidst the brutal debris of war becomes increasingly nightmarish, a battle between despair and hope.",
    popularity: 20.551,
    poster_path: "/qNbMsKVzigERgJUbwf8pKyZogpb.jpg",
    release_date: "1985-10-17",
    title: "Come and See",
    video: false,
    vote_average: 8.256,
    vote_count: 1472,
  },
  {
    adult: false,
    backdrop_path: "/27ZkYMWynuK2qiDP6awc3MsCaOs.jpg",
    genre_ids: [10749, 18],
    id: 527641,
    original_language: "en",
    original_title: "Five Feet Apart",
    overview:
      "Seventeen-year-old Stella spends most of her time in the hospital as a cystic fibrosis patient. Her life is full of routines, boundaries and self-control — all of which get put to the test when she meets Will, an impossibly charming teen who has the same illness. There's an instant flirtation, though restrictions dictate that they must maintain a safe distance between them. As their connection intensifies, so does the temptation to throw the rules out the window and embrace that attraction.",
    popularity: 42.552,
    poster_path: "/kreTuJBkUjVWePRfhHZuYfhNE1T.jpg",
    release_date: "2019-03-14",
    title: "Five Feet Apart",
    video: false,
    vote_average: 8.254,
    vote_count: 5578,
  },
  {
    adult: false,
    backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    genre_ids: [12, 878, 28],
    id: 299534,
    original_language: "en",
    original_title: "Avengers: Endgame",
    overview:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    popularity: 168.942,
    poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    release_date: "2019-04-24",
    title: "Avengers: Endgame",
    video: false,
    vote_average: 8.249,
    vote_count: 25530,
  },
  {
    adult: false,
    backdrop_path: "/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg",
    genre_ids: [12, 28, 878],
    id: 299536,
    original_language: "en",
    original_title: "Avengers: Infinity War",
    overview:
      "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
    popularity: 236.214,
    poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    release_date: "2018-04-25",
    title: "Avengers: Infinity War",
    video: false,
    vote_average: 8.243,
    vote_count: 29640,
  },
  {
    adult: false,
    backdrop_path: "/2Xe9lISpwXKhvKiHttbFfVRERQX.jpg",
    genre_ids: [18, 36],
    id: 490132,
    original_language: "en",
    original_title: "Green Book",
    overview:
      "Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.",
    popularity: 44.493,
    poster_path: "/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg",
    release_date: "2018-11-16",
    title: "Green Book",
    video: false,
    vote_average: 8.24,
    vote_count: 11518,
  },
  {
    adult: false,
    backdrop_path: "/mlxKite1x1PgmIhJgAxNS9eHmH8.jpg",
    genre_ids: [16, 10751, 12, 35, 14],
    id: 508965,
    original_language: "en",
    original_title: "Klaus",
    overview:
      "When Jesper distinguishes himself as the Postal Academy's worst student, he is sent to Smeerensburg, a small village located on an icy island above the Arctic Circle, where grumpy inhabitants barely exchange words, let alone letters. Jesper is about to give up and abandon his duty as a postman when he meets local teacher Alva and Klaus, a mysterious carpenter who lives alone in a cabin full of handmade toys.",
    popularity: 31.846,
    poster_path: "/q125RHUDgR4gjwh1QkfYuJLYkL.jpg",
    release_date: "2019-11-08",
    title: "Klaus",
    video: false,
    vote_average: 8.239,
    vote_count: 3970,
  },
  {
    adult: false,
    backdrop_path: "/dIHezuC3AmylT8mkXQiWSjz2wJR.jpg",
    genre_ids: [18],
    id: 265177,
    original_language: "fr",
    original_title: "Mommy",
    overview:
      "A peculiar neighbor offers hope to a recent widow who is struggling to raise a teenager who is unpredictable and, sometimes, violent.",
    popularity: 17.916,
    poster_path: "/3zyQtPg3avKprmJP2gBiYgyWUQC.jpg",
    release_date: "2014-09-19",
    title: "Mommy",
    video: false,
    vote_average: 8.238,
    vote_count: 2702,
  },
  {
    adult: false,
    backdrop_path: "/tyxqfALuq02khuKNCwmeMxrqt8T.jpg",
    genre_ids: [16, 10749, 18, 14],
    id: 572154,
    original_language: "ja",
    original_title: "青春ブタ野郎はゆめみる少女の夢を見ない",
    overview:
      "In Fujisawa, Sakuta Azusagawa is in his second year of high school. Blissful days with his girlfriend and upperclassman, Mai Sakurajima, are interrupted by the appearance of his first crush, Shoko Makinohara.",
    popularity: 15.059,
    poster_path: "/gsRpizQa3fw1um8v7EvFVXvxD6u.jpg",
    release_date: "2019-06-15",
    title: "Rascal Does Not Dream of a Dreaming Girl",
    video: false,
    vote_average: 8.2,
    vote_count: 519,
  },
  {
    adult: false,
    backdrop_path: "/eNWjMbuhGxJdzaIY9ZZ2KvWx2sQ.jpg",
    genre_ids: [16, 10751, 18, 14],
    id: 110420,
    original_language: "ja",
    original_title: "おおかみこどもの雨と雪",
    overview:
      "After her werewolf lover unexpectedly dies in an accident, a woman must find a way to raise the son and daughter that she had with him. However, their inheritance of their father's traits prove to be a challenge for her.",
    popularity: 33.5,
    poster_path: "/3Nllh6JgcrFdtOn6iFOWHudNInd.jpg",
    release_date: "2012-07-21",
    title: "Wolf Children",
    video: false,
    vote_average: 8.227,
    vote_count: 2273,
  },
  {
    adult: false,
    backdrop_path: "/yeJhRNtE4XW2lOoVVFO9iuDr3AL.jpg",
    genre_ids: [16, 10751, 12, 14],
    id: 441130,
    original_language: "en",
    original_title: "Wolfwalkers",
    overview:
      "In a time of superstition and magic, when wolves are seen as demonic and nature an evil to be tamed, a young apprentice hunter comes to Ireland with her father to wipe out the last pack. But when she saves a wild native girl, their friendship leads her to discover the world of the Wolfwalkers and transform her into the very thing her father is tasked to destroy.",
    popularity: 20.618,
    poster_path: "/53VE3Iv9NiCOJfFMWwQuRUQMaXZ.jpg",
    release_date: "2020-10-26",
    title: "Wolfwalkers",
    video: false,
    vote_average: 8.226,
    vote_count: 1178,
  },
];
